#theme: jekyll-theme-architect
remote_theme: pmarsceill/just-the-docs

title: V3 tutorial

search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "访问速易天工V3官网":
    - "https://www.6erp.cn/portfoliotype/messp"
